replicaCount: 2
name: trivial-go-web-app
env: staging
namespace: staging
image:
  name: webserver-simple
  tag: 'a9f44751c23820745efef75e7a053b3ed8da6f8a'
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 8419
  targetPort: 8080
  portName: http
