replicaCount: 1
name: jfrog-nginx
env: staging
namespace: staging
image:
  name: jfrog-nginx
  tag: 'a9f44751c23820745efef75e7a053b3ed8da6f8a'
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 8418
  targetPort: 8080
  portName: http
